plugins {
    id 'java'
    id 'name.jurgenei.gradle.antlr.sas'
}

tasks.named('ds2XmlAst', name.jurgenei.gradle.antlr.XmlAstDs2GradleTask) {
    sourceDirectory.set(layout.projectDirectory.dir('src/main/ds2'))
    destinationDirectory.set(layout.buildDirectory.dir('output/ds2/xmlast'))
    targetExtension.set('.xml')
}

tasks.named('ds2Semantic', name.jurgenei.gradle.antlr.Ds2SemanticExtractGradleTask) {
    sourceDirectory.set(layout.projectDirectory.dir('src/main/ds2'))
    destinationDirectory.set(layout.buildDirectory.dir('output/ds2/semantic'))
}

